My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<slug:category>/', views.post_list, name='post_list_by_category'),
    path('post/<int:id>', views.post_detail, name='post_detail'),
    path('post/<int:id>/comment', views.post_comment, name='post_comment'),
    path('contact-us/', views.ticket, name='ticket'),
    path('posts/search', views.post_search, name='post_search'),
    path('profile/', views.profile_posts, name='profile_posts'),
    path('profile/create_post', views.create_post, name='create_post'),
    path('profile/delete_post/<int:id>', views.delete_post, name='delete_post'),
    path('profile/edit_post/<int:id>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<int:image_id>', views.delete_image, name='delete_image'),
    path('profile/personal_detail', views.personal_detail, name='personal_detail'),
    path('profile/edit_personal_detail', views.edit_personal_detail, name='edit_personal_detail'),
    path('change_password/', views.change_password, name='change_password'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),

]

blog/forms.py
from django import forms
from .models import Post, Comment, User, Account


# =====================================<< Ticket Form >>=====================================
class TicketForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


# =====================================<< Comment Form >>=====================================
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', 'send_mail']


# =====================================<< Search Form >>=====================================
class SearchForm(forms.Form):
    query = forms.CharField()


# =====================================<< Create Post Form >>=====================================
class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    category = forms.CharField(max_length=250)

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time']


# =====================================<< Login Form >>=====================================
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


# =====================================<< User Edit Form >>=====================================
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


# =====================================<< Account Edit Form >>=====================================
class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['job', 'bio', 'date_of_birth', 'image']


# =====================================<< Change Password Form >>=====================================
class ChangePasswordForm(forms.Form):
    password = forms.CharField(required=True)
    new_password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    # def clean_new_password(self):
    #     cd = self.cleaned_data
    #     if cd['new_password'] != cd['confirm_password']:
    #         raise forms.ValidationError("رمز ها تطابق ندارند")
    #     else:
    #         return cd['new_password']


# =====================================<< Register Form >>=====================================
class RegisterForm(forms.ModelForm):
    password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    # username = forms.CharField(max_length=100, required=True)
    # first_name = forms.CharField(max_length=250, required=True)
    # last_name = forms.CharField(max_length=250, required=True)
    # email = forms.EmailField(max_length=250, required=True)

blog/views.py
import django.forms
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity, SearchRank, SearchQuery, SearchVector
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth import password_validation, update_session_auth_hash


# =====================================<< Index View >>=====================================
def index(request):
    return render(request, 'blog/index.html', {})


# =====================================<< Post List View >>=====================================
def post_list(request, category=None):
    posts = Post.published.all()

    if category:
        posts = posts.filter(category__slug=category)

    print(category)

    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Post Detail View >>=====================================
def post_detail(request, id):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=id)
    comments = post.comments.filter(active=True)

    context = {
        'post': post,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# =====================================<< Post Search View >>=====================================
def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_query = SearchQuery(query)
            search_vector = SearchVector('title', 'description')
            search_rank = SearchRank(search_vector, search_query)
            results = Post.published.annotate(search=search_vector, rank=search_rank)\
                .filter(search=search_query).order_by('-rank')

            # results_1 = Post.published.annotate(similarity=TrigramSimilarity('title', query))\
            #     .filter(similarity__gte=0.1)
            # results_2 = Post.published.annotate(similarity=TrigramSimilarity('description', query))\
            #     .filter(similarity__gte=0.1)
            # results = (results_1 | results_2).order_by('-similarity')

    paginator = Paginator(results, 6)
    page_number = request.GET.get('page', 1)
    try:
        results = paginator.page(page_number)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        'query': query,
        'posts': results,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Profile Posts View >>=====================================
def profile_posts(request):
    user = request.user
    posts = Post.objects.filter(auther=user)
    context = {
        'posts': posts
    }

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Edit Personal Detail View >>=====================================
def edit_personal_detail(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_from = AccountEditForm(request.POST, files=request.FILES, instance=request.user.account)
        print(user_form.is_valid(), account_from.is_valid())
        if user_form.is_valid() and account_from.is_valid():

            if request.FILES['image']:
                old_image = request.user.account.image
                storage, path = old_image.storage, old_image.path
                storage.delete(path)
                print(old_image)

            user_form.save(commit=True)
            account_from.save(commit=True)
            return redirect('blog:personal_detail')
    else:
        user_form = UserEditForm(instance=request.user)
        account_from = AccountEditForm(instance=request.user.account)

    return render(request, 'forms/edit_personal_detail.html', {})


# =====================================<< Logout View >>=====================================
def change_password(request):
    user = request.user
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            password = cd['password']
            new_password = cd['new_password']
            confirm_password = cd['confirm_password']
            if user.check_password(password):
                user.set_password(new_password)
                update_session_auth_hash(request, user)
                user.save()
                print("با موفقیت عوض شد")
            else:
                return HttpResponse("رمز فعلی را اشتباه وارد کردید.")
    else:
        form = ChangePasswordForm()

    return render(request, 'forms/change_password.html', {})


# =====================================<< Profile Personal Detail View >>=====================================
def personal_detail(request):
    return render(request, 'blog/profile-personal.html', {})


# =====================================<< Login View >>=====================================
def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            cd = form.cleaned_data
            username = User.objects.get(email=cd['email'].lower()).username
            print(username)
            user = authenticate(request, username=username, password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile_posts')
                else:
                    return HttpResponse("Your account is disabled.")
            else:
                return HttpResponse('User Not Found.(user or pass is wrong)')
    else:
        form = LoginForm()

    return render(request, 'forms/login.html', {'form': form})


# =====================================<< Logout View >>=====================================
def logout_user(request):
    logout(request)
    return redirect('blog:post_list')


# =====================================<< Login View >>=====================================
def register(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = form.save(commit=False)
            user.set_password(cd['password'])
            user.save()
            Account.objects.create(user=user)

            return redirect('blog:login')
    else:
        form = RegisterForm(request.POST)

    return render(request, 'forms/register.html', {'form': form})


# =====================================<< Create Post View >>=====================================
def create_post(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            # print(cd)

            post = form.save(commit=False)
            post.auther = request.user
            post.category = Category.objects.get(name=cd['category'])
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)

    else:
        form = CreatePostForm()

    return render(request, 'blog/create-post.html', {'form': form, 'categories': categories})


# =====================================<< Edit Post View >>=====================================
def edit_post(request, id):
    post = get_object_or_404(Post, id=id)
    categories = Category.objects.all()
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            cd = form.cleaned_data
            post = form.save(commit=False)
            post.auther = request.user
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)
    else:
        form = CreatePostForm(instance=post)

    context = {
        'form': form,
        'post': post,
        'categories': categories
    }

    return render(request, 'blog/create-post.html', context)


# =====================================<< Delete Post View >>=====================================
def delete_post(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()

    posts = Post.published.filter(auther=request.user)
    context = {
        'posts': posts
    }

    print(posts)
    if not post.id:
        return redirect('blog:profile_posts')

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Delete Image View >>=====================================
def delete_image(request, image_id):

    image = get_object_or_404(Image, id=image_id)
    post_id = image.post.id
    image.delete()

    return redirect('blog:edit_post', post_id)


# =====================================<< Ticket View >>=====================================
def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

blog/templates/partials/footer.html
{% load static %}
{% load jformat %}
{% load blog_tags %}

<footer class="footer">
    <div class="container">
        <div class="footer-wrapper">

            <div class="footer-box">
                <div class="footer-box-top">
                    <h2 class="footer-box__title">آخرین مقالات</h2>
                    <span class="footer-box__line"></span>
                </div>
                <div class="footer-box-bottom">

                    {% last_posts 2 as last_posts %}
                    {% for post in last_posts %}
                        <div class="footer-post">
                        <a href="{{ post.get_absolute_url }}" class="footer-post__image-wrapper">
                            {% if post.images.all %}
                               <img class="post__image" src="{{ post.images.first.image_file.url }}" alt="#">
                            {% else %}
                               <img class="post__image" src="{% static 'images/image-not-found.png' %}" alt="#">
                            {% endif %}                        </a>
                        <div class="footer-post-contetnt">
                            <a class="footer-post__title" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            <p class="footer-post__date" >{{ post.publish|jformat:"%d %Y %B" }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="footer-box">
                <div class="footer-box-top">
                    <h2 class="footer-box__title">ابر برچسب ها</h2>
                    <span class="footer-box__line"></span>
                </div>
                <div class="footer-box-bottom">
                    <div class="footer__tags">
                        {% popular_tags 6 as pop_tags %}
                        {% for tag in pop_tags %}
                            <a href="{% url 'blog:post_list_by_category' tag.slug %}" class="footer__tag">#{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="footer-box">
                <div class="footer-box-top">
                    <h2 class="footer-box__title">مرا دنبال کنید!</h2>
                    <span class="footer-box__line"></span>
                </div>
                <div class="footer-box-bottom">
                    <div class="followme">
                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="250" height="250" viewBox="0 0 50 50"
                            style="fill:#FFFFFF;">
                            <path d="M25,2c12.703,0,23,10.297,23,23S37.703,48,25,48S2,37.703,2,25S12.297,2,25,2z M32.934,34.375	c0.423-1.298,2.405-14.234,2.65-16.783c0.074-0.772-0.17-1.285-0.648-1.514c-0.578-0.278-1.434-0.139-2.427,0.219	c-1.362,0.491-18.774,7.884-19.78,8.312c-0.954,0.405-1.856,0.847-1.856,1.487c0,0.45,0.267,0.703,1.003,0.966	c0.766,0.273,2.695,0.858,3.834,1.172c1.097,0.303,2.346,0.04,3.046-0.395c0.742-0.461,9.305-6.191,9.92-6.693	c0.614-0.502,1.104,0.141,0.602,0.644c-0.502,0.502-6.38,6.207-7.155,6.997c-0.941,0.959-0.273,1.953,0.358,2.351	c0.721,0.454,5.906,3.932,6.687,4.49c0.781,0.558,1.573,0.811,2.298,0.811C32.191,36.439,32.573,35.484,32.934,34.375z"></path>
                            </svg>
                        </a>

                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="250" height="250" viewBox="0 0 50 50"
                            style="fill:#FFFFFF;">
                                <path d="M 16 3 C 8.83 3 3 8.83 3 16 L 3 34 C 3 41.17 8.83 47 16 47 L 34 47 C 41.17 47 47 41.17 47 34 L 47 16 C 47 8.83 41.17 3 34 3 L 16 3 z M 37 11 C 38.1 11 39 11.9 39 13 C 39 14.1 38.1 15 37 15 C 35.9 15 35 14.1 35 13 C 35 11.9 35.9 11 37 11 z M 25 14 C 31.07 14 36 18.93 36 25 C 36 31.07 31.07 36 25 36 C 18.93 36 14 31.07 14 25 C 14 18.93 18.93 14 25 14 z M 25 16 C 20.04 16 16 20.04 16 25 C 16 29.96 20.04 34 25 34 C 29.96 34 34 29.96 34 25 C 34 20.04 29.96 16 25 16 z"></path>
                            </svg>
                        </a>

                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="250" height="250" viewBox="0 0 50 50"
                            style="fill:#FFFFFF;">
                                <path d="M25,2C12.318,2,2,12.317,2,25s10.318,23,23,23c12.683,0,23-10.317,23-23S37.683,2,25,2z M32,16h-3.29 C26.772,16,26,16.455,26,17.806V21h6l-1,5h-5v13h-6V26h-3v-5h3v-2.774C20,14.001,21.686,11,26.581,11C29.203,11,32,12,32,12V16z"></path>
                            </svg>
                        </a>

                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="512" height="512" viewBox="0 0 64 64"
                            style="fill:#FFFFFF;">
                            <path d="M32 6C17.641 6 6 17.641 6 32c0 12.277 8.512 22.56 19.955 25.286-.592-.141-1.179-.299-1.755-.479V50.85c0 0-.975.325-2.275.325-3.637 0-5.148-3.245-5.525-4.875-.229-.993-.827-1.934-1.469-2.509-.767-.684-1.126-.686-1.131-.92-.01-.491.658-.471.975-.471 1.625 0 2.857 1.729 3.429 2.623 1.417 2.207 2.938 2.577 3.721 2.577.975 0 1.817-.146 2.397-.426.268-1.888 1.108-3.57 2.478-4.774-6.097-1.219-10.4-4.716-10.4-10.4 0-2.928 1.175-5.619 3.133-7.792C19.333 23.641 19 22.494 19 20.625c0-1.235.086-2.751.65-4.225 0 0 3.708.026 7.205 3.338C28.469 19.268 30.196 19 32 19s3.531.268 5.145.738c3.497-3.312 7.205-3.338 7.205-3.338.567 1.474.65 2.99.65 4.225 0 2.015-.268 3.19-.432 3.697C46.466 26.475 47.6 29.124 47.6 32c0 5.684-4.303 9.181-10.4 10.4 1.628 1.43 2.6 3.513 2.6 5.85v8.557c-.576.181-1.162.338-1.755.479C49.488 54.56 58 44.277 58 32 58 17.641 46.359 6 32 6zM33.813 57.93C33.214 57.972 32.61 58 32 58 32.61 58 33.213 57.971 33.813 57.93zM37.786 57.346c-1.164.265-2.357.451-3.575.554C35.429 57.797 36.622 57.61 37.786 57.346zM32 58c-.61 0-1.214-.028-1.813-.07C30.787 57.971 31.39 58 32 58zM29.788 57.9c-1.217-.103-2.411-.289-3.574-.554C27.378 57.61 28.571 57.797 29.788 57.9z"></path>
                            </svg>
                        </a>

                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="512" height="512" viewBox="0 0 64 64"
                            style="fill:#FFFFFF;">
                            <path d="M32,6C17.641,6,6,17.641,6,32c0,14.359,11.641,26,26,26s26-11.641,26-26C58,17.641,46.359,6,32,6z M44.927,26.226 c0.012,0.271,0.017,0.543,0.017,0.816c0,8.34-6.189,17.958-17.51,17.958c-3.476,0-6.711-1.045-9.435-2.835 c0.482,0.059,0.973,0.089,1.469,0.089c2.884,0,5.538-1.009,7.644-2.702c-2.693-0.051-4.966-1.877-5.749-4.384 c0.375,0.072,0.761,0.112,1.157,0.112c0.562,0,1.107-0.077,1.622-0.221c-2.816-0.579-4.937-3.13-4.937-6.188 c0-0.027,0-0.052,0-0.079c0.83,0.472,1.779,0.756,2.788,0.789c-1.651-1.131-2.737-3.063-2.737-5.252 c0-1.158,0.303-2.242,0.832-3.175c3.037,3.819,7.571,6.333,12.686,6.595c-0.104-0.46-0.159-0.943-0.159-1.438 c0-3.485,2.755-6.311,6.154-6.311c1.77,0,3.369,0.767,4.492,1.994c1.403-0.284,2.721-0.809,3.909-1.532 c-0.459,1.474-1.434,2.711-2.706,3.492C45.71,23.8,46.896,23.462,48,22.959C47.175,24.224,46.131,25.335,44.927,26.226z"></path>
                            </svg>
                        </a>

                        <a href="#" class="followme__link">
                            <svg class="followme__svg" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="512" height="512" viewBox="0 0 64 64"
                            style="fill:#FFFFFF;">
                            <path d="M32,6C17.641,6,6,17.641,6,32c0,14.359,11.641,26,26,26s26-11.641,26-26C58,17.641,46.359,6,32,6z M25,44h-5V26h5V44z M22.485,24h-0.028C20.965,24,20,22.888,20,21.499C20,20.08,20.995,19,22.514,19c1.521,0,2.458,1.08,2.486,2.499 C25,22.887,24.035,24,22.485,24z M44,44h-5v-9c0-3-1.446-4-3-4c-1.445,0-3,1-3,4v9h-5V26h5v3c0.343-0.981,1.984-3,5-3c4,0,6,3,6,8 V44z"></path>
                            </svg>
                        </a>


                    </div>
                </div>
            </div>

            <div class="footer-box">
                <div class="footer-box-top">
                    <h2 class="footer-box__title">درباره من</h2>
                    <span class="footer-box__line"></span>
                </div>
                <div class="footer-box-bottom">
                    <div class="about-me">
                        <div class="about-me-top">
                            <a href="#" class="about-me__image-wrapper">
                                <img class="about-me__image" src="{% static 'images/mahdi.jpg' %}" alt="#">
                            </a>
                            <a href="#" class="about-me__name">مهدی رنجبر</a>
                        </div>
                        <p class="about-me__description">سلام!من مهدی رنجبر هستم برنامه نویس بک اند.فرانتم دوست دارم ولی بک اند یه چیزه دیگست/راجع به هوش مصنوعیم گاهی مطالعه میکنم. فیلد جذابیه.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</footer>

blog/templates/partials/navigation.html
<div class="nav-wrapper">
    <nav class="nav">
        <a class="nav__logo" href="#"><span class="nav__logo--blue">و</span>بلاگ</a>
        <ul class="menu">
            <li class="menu__item"><a href="{% url 'blog:post_list' %}" class="menu__item-link">صفحه اصلی</a></li>
            <li class="menu__item"><a href="#" class="menu__item-link">درباره ما</a></li>
            <li class="menu__item"><a href="{% url 'blog:ticket' %}" class="menu__item-link">تماس با ما</a></li>
        </ul>
        {% if request.user.is_authenticated %}
            <a href="{% url 'blog:profile_posts' %}" class="nav__btn">
                {{ request.user.first_name }} {{ request.user.last_name }}
                <a href="{% url 'blog:logout' %}" class="nav__btn-exit">خروج</a>
            </a>
        {% else  %}
            <a href="{% url 'blog:login' %}" class="nav__btn">
                ورود | ثبت نام
            </a>
        {% endif %}
    </nav>
</div>

blog/templates/partials/pagination.html
<div class="pagination">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" class="pagination__previous">قبل</a>
    {% endif %}

    <span class="pagination__pages">صفحه {{ page.number }} از {{ page.paginator.num_pages }}</span>

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" class="pagination__next">بعد</a>
    {% endif %}
</div>

blog/templates/partials/search.html
<form method="get" action="{% url 'blog:post_search' %}" class="search">

    <div class="search-svg-wrapper">
        <svg class="search__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" >
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
        </svg>
        <input type="submit" class="search__submit" value="">
    </div>


    <input type="text" name="query" class="search__input" placeholder="جستجو..."/>
</form>