My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<slug:category>/', views.post_list, name='post_list_by_category'),
    path('post/<int:id>', views.post_detail, name='post_detail'),
    path('post/<int:id>/comment', views.post_comment, name='post_comment'),
    path('contact-us/', views.ticket, name='ticket'),
    path('posts/search', views.post_search, name='post_search'),
    path('profile/', views.profile_posts, name='profile_posts'),
    path('profile/create_post', views.create_post, name='create_post'),
    path('profile/delete_post/<int:id>', views.delete_post, name='delete_post'),
    path('profile/edit_post/<int:id>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<int:image_id>', views.delete_image, name='delete_image'),
    path('profile/personal_detail', views.personal_detail, name='personal_detail'),
    path('profile/edit_personal_detail', views.edit_personal_detail, name='edit_personal_detail'),
    path('change_password/', views.change_password, name='change_password'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),

]

blog/forms.py
from django import forms
from .models import Post, Comment, User, Account


# =====================================<< Ticket Form >>=====================================
class TicketForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


# =====================================<< Comment Form >>=====================================
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', 'send_mail']


# =====================================<< Search Form >>=====================================
class SearchForm(forms.Form):
    query = forms.CharField()


# =====================================<< Create Post Form >>=====================================
class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    category = forms.CharField(max_length=250)

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time']


# =====================================<< Login Form >>=====================================
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


# =====================================<< User Edit Form >>=====================================
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


# =====================================<< Account Edit Form >>=====================================
class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['job', 'bio', 'date_of_birth', 'image']


# =====================================<< Change Password Form >>=====================================
class ChangePasswordForm(forms.Form):
    password = forms.CharField(required=True)
    new_password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    # def clean_new_password(self):
    #     cd = self.cleaned_data
    #     if cd['new_password'] != cd['confirm_password']:
    #         raise forms.ValidationError("رمز ها تطابق ندارند")
    #     else:
    #         return cd['new_password']


# =====================================<< Register Form >>=====================================
class RegisterForm(forms.ModelForm):
    password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    # username = forms.CharField(max_length=100, required=True)
    # first_name = forms.CharField(max_length=250, required=True)
    # last_name = forms.CharField(max_length=250, required=True)
    # email = forms.EmailField(max_length=250, required=True)

blog/views.py
import django.forms
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity, SearchRank, SearchQuery, SearchVector
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth import password_validation, update_session_auth_hash


# =====================================<< Index View >>=====================================
def index(request):
    return render(request, 'blog/index.html', {})


# =====================================<< Post List View >>=====================================
def post_list(request, category=None):
    posts = Post.published.all()

    if category:
        posts = posts.filter(category__slug=category)

    print(category)

    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Post Detail View >>=====================================
def post_detail(request, id):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=id)
    comments = post.comments.filter(active=True)

    context = {
        'post': post,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# =====================================<< Post Search View >>=====================================
def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_query = SearchQuery(query)
            search_vector = SearchVector('title', 'description')
            search_rank = SearchRank(search_vector, search_query)
            results = Post.published.annotate(search=search_vector, rank=search_rank)\
                .filter(search=search_query).order_by('-rank')

            # results_1 = Post.published.annotate(similarity=TrigramSimilarity('title', query))\
            #     .filter(similarity__gte=0.1)
            # results_2 = Post.published.annotate(similarity=TrigramSimilarity('description', query))\
            #     .filter(similarity__gte=0.1)
            # results = (results_1 | results_2).order_by('-similarity')

    paginator = Paginator(results, 6)
    page_number = request.GET.get('page', 1)
    try:
        results = paginator.page(page_number)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        'query': query,
        'posts': results,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Profile Posts View >>=====================================
def profile_posts(request):
    user = request.user
    posts = Post.objects.filter(auther=user)
    context = {
        'posts': posts
    }

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Edit Personal Detail View >>=====================================
def edit_personal_detail(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_from = AccountEditForm(request.POST, files=request.FILES, instance=request.user.account)
        print(user_form.is_valid(), account_from.is_valid())
        if user_form.is_valid() and account_from.is_valid():

            if request.FILES['image']:
                old_image = request.user.account.image
                storage, path = old_image.storage, old_image.path
                storage.delete(path)
                print(old_image)

            user_form.save(commit=True)
            account_from.save(commit=True)
            return redirect('blog:personal_detail')
    else:
        user_form = UserEditForm(instance=request.user)
        account_from = AccountEditForm(instance=request.user.account)

    return render(request, 'forms/edit_personal_detail.html', {})


# =====================================<< Logout View >>=====================================
def change_password(request):
    user = request.user
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            password = cd['password']
            new_password = cd['new_password']
            confirm_password = cd['confirm_password']
            if user.check_password(password):
                user.set_password(new_password)
                update_session_auth_hash(request, user)
                user.save()
                print("با موفقیت عوض شد")
            else:
                return HttpResponse("رمز فعلی را اشتباه وارد کردید.")
    else:
        form = ChangePasswordForm()

    return render(request, 'forms/change_password.html', {})


# =====================================<< Profile Personal Detail View >>=====================================
def personal_detail(request):
    return render(request, 'blog/profile-personal.html', {})


# =====================================<< Login View >>=====================================
def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            cd = form.cleaned_data
            username = User.objects.get(email=cd['email'].lower()).username
            print(username)
            user = authenticate(request, username=username, password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile_posts')
                else:
                    return HttpResponse("Your account is disabled.")
            else:
                return HttpResponse('User Not Found.(user or pass is wrong)')
    else:
        form = LoginForm()

    return render(request, 'forms/login.html', {'form': form})


# =====================================<< Logout View >>=====================================
def logout_user(request):
    logout(request)
    return redirect('blog:post_list')


# =====================================<< Login View >>=====================================
def register(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = form.save(commit=False)
            user.set_password(cd['password'])
            user.save()
            Account.objects.create(user=user)

            return redirect('blog:login')
    else:
        form = RegisterForm(request.POST)

    return render(request, 'forms/register.html', {'form': form})


# =====================================<< Create Post View >>=====================================
def create_post(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            # print(cd)

            post = form.save(commit=False)
            post.auther = request.user
            post.category = Category.objects.get(name=cd['category'])
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)

    else:
        form = CreatePostForm()

    return render(request, 'blog/create-post.html', {'form': form, 'categories': categories})


# =====================================<< Edit Post View >>=====================================
def edit_post(request, id):
    post = get_object_or_404(Post, id=id)
    categories = Category.objects.all()
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            cd = form.cleaned_data
            post = form.save(commit=False)
            post.auther = request.user
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)
    else:
        form = CreatePostForm(instance=post)

    context = {
        'form': form,
        'post': post,
        'categories': categories
    }

    return render(request, 'blog/create-post.html', context)


# =====================================<< Delete Post View >>=====================================
def delete_post(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()

    posts = Post.published.filter(auther=request.user)
    context = {
        'posts': posts
    }

    print(posts)
    if not post.id:
        return redirect('blog:profile_posts')

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Delete Image View >>=====================================
def delete_image(request, image_id):

    image = get_object_or_404(Image, id=image_id)
    post_id = image.post.id
    image.delete()

    return redirect('blog:edit_post', post_id)


# =====================================<< Ticket View >>=====================================
def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

blog/templates/forms/change_password.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Change Password{% endblock %}

{% block content %}
    <div class="container">
        <div class="login">
            <div class="contactus">
                <h2 class="contactus__title">تغییر رمز</h2>
                <form method="post" class="contactus__form">
                    {% csrf_token %}
                    <div class="login-inputs-wrapper">
                        <label for="ticket__email" class="contactus__label">رمز عبور فعلی</label>
                        <input name="password" type="password" id="ticket__email" required class="ticket__email">
                    </div>

                    <div class="login-inputs-wrapper">
                        <label for="ticket__email" class="contactus__label">رمز عبور جدید</label>
                        <input name="new_password" type="password" id="ticket__email" required class="ticket__email">
                    </div>

                    <div class="login-inputs-wrapper">
                        <label for="ticket__name" class="contactus__label">تکرار رمز جدید</label>
                        <input name="confirm_password" type="password" id="ticket__name" required class="ticket__name">
                    </div>


                    <input type="submit" class="comment-form__btn" value="تغییر رمز">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/forms/comment.html
<div class="post-comment-form-wrapper">
    <div class="footer-box-top">
        <h2 class="footer-box__title">دیدگاهتان را بنویسید</h2>
        <span class="footer-box__line"></span>
    </div>
    <form action="{% url 'blog:post_comment' post.id %}" method="post" class="comment">
        {% csrf_token %}
        <textarea name="body" id="" cols="30" rows="10" class="comment__description" placeholder="دیدگاه" required></textarea>
        <div class="comment-input-wrapper">
            <input name="name" type="text" required placeholder="نام" class="comment__name">
            <input name="email" type="email" required placeholder="ایمیل" class="comment__email">
        </div>

        <div class="comment-checkbox-wrapper">
            <input type="checkbox" name="send_mail" id="comment__ckeck" class="comment__ckeck">
            <label for="comment__ckeck" class="comment__check-label">ذخیره نام، ایمیل و وبسایت من در مرورگر برای زمانی که دوباره دیدگاهی می‌نویسم.</label>
        </div>
        <input type="submit" class="comment-form__btn" value="فرستادن دیدگاه">
    </form>
</div>

blog/templates/forms/edit_personal_detail.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Profile | Edit Personal Detail{% endblock %}

{% block content %}
    <div class="container">
        <div class="contactus">
            <h2 class="contactus__title">ویرایش اطلاعات شخصی</h2>
            <form method="post" enctype="multipart/form-data" class="contactus__form">
                {% csrf_token %}
                <div class="contactus-top">
                    <div class="contactus__elemetnt-wrapper">
                        <label for="ticket__email" class="contactus__label">نام</label>
                        <input name="first_name" type="text" id="ticket__email" required class="ticket__email">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">نام خانوادگی</label>
                        <input name="last_name" type="text" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" style="width: 100%;">
                        <label for="ticket__phone" class="contactus__label" >ایمیل</label>
                        <input name="email" type="email" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">شغل</label>
                        <input name="job" type="text" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">تاریخ تولد</label>
                        <input name="date_of_birth" type="date" id="ticket__phone" required class="ticket__phone">
                    </div>
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__description" class="contactus__label">بایو</label>
                    <textarea name="bio" id="ticket__description" cols="30" rows="10" class="ticket__description" ></textarea>
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <span class="contactus__label">تصویر پروفایل</span>
                    <input  class="image-upload" type="file" name="image" id="" >
                </div>
                <input type="submit" class="comment-form__btn" value="ویرایش">
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/forms/login.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <div class="login">
            <div class="contactus">
                <h2 class="contactus__title">ورود</h2>
                <form method="post" class="contactus__form">
                    {% csrf_token %}
                    <div class="login-inputs-wrapper">
                        <label for="ticket__email" class="contactus__label">ایمیل</label>
                        <input name="email" type="email" id="ticket__email" required class="ticket__email">
                    </div>

                    <div class="login-inputs-wrapper">
                        <label for="ticket__name" class="contactus__label">رمز</label>
                        <input name="password" type="password" id="ticket__name" required class="ticket__name">
                    </div>


                    <input type="submit" class="comment-form__btn" value="ورود">
                </form>
                <div class="login-links">
                    <a href="#" class="login-link">فراموشی رمز عبور</a>
                    <br>
                    <a href="{% url 'blog:register' %}" class="login-link">ایجاد حساب</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/forms/register.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
    <div class="container">
        <div class="contactus">
            <h2 class="contactus__title">ثبت نام</h2>
            <form method="post" class="contactus__form">
                {% csrf_token %}
                <div class="contactus-top">
                    <div class="contactus__elemetnt-wrapper"  style="width: 100%;">
                        <label for="ticket__name" class="contactus__label">نام کاربری</label>
                        <input name="username" type="text" id="ticket__name" required class="ticket__name">
                    </div>

                    <div class="contactus__elemetnt-wrapper">
                        <label for="ticket__email" class="contactus__label">نام</label>
                        <input name="first_name" type="text" id="ticket__email" required class="ticket__email">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">نام خانوادگی</label>
                        <input name="last_name" type="text" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" style="width: 100%;">
                        <label for="ticket__phone" class="contactus__label" >ایمیل</label>
                        <input name="email" type="email" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">رمز عبور</label>
                        <input name="password" type="password" id="ticket__phone" required class="ticket__phone">
                    </div>

                    <div class="contactus__elemetnt-wrapper" >
                        <label for="ticket__phone" class="contactus__label">تکرار رمز عبور</label>
                        <input name="confirm_password" type="password" id="ticket__phone" required class="ticket__phone">
                    </div>
                </div>

                <input type="submit" class="comment-form__btn" value="ثبت نام">
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/forms/ticket.html
<div class="container">
    <div class="contactus">
        <h2 class="contactus__title">تماس با ما</h2>
        <form method="post" class="contactus__form">
            {% csrf_token %}
            <div class="contactus-top">
                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__name" class="contactus__label">نام</label>
                    <input type="text" name="name" id="ticket__name" required class="ticket__name">
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__email" class="contactus__label">ایمیل</label>
                    <input type="email" name="email" id="ticket__email" required class="ticket__email">
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__phone" class="contactus__label">شماره همراه</label>
                    <input type="tel" name="phone" id="ticket__phone" required class="ticket__phone">
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__select" class="contactus__label">موضوع</label>
                    <select name="subject" id="ticket__select" class="ticket__select">
                        <option value="انتقاد">انتقاد</option>
                        <option value="پیشنهاد">پیشنهاد</option>
                        <option value="گزارش">گزارش</option>
                        <option value="درخواست تماس">درخواست تماس</option>
                    </select>
                </div>
            </div>

            <div class="contactus__elemetnt-wrapper">
                <label for="ticket__description" class="contactus__label">دیدگاه</label>
                <textarea name="message" id="ticket__description" cols="30" rows="10" class="ticket__description" ></textarea>
            </div>

            <input type="submit" class="comment-form__btn" value="ارسال درخواست">
        </form>
    </div>
</div>