My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<slug:category>/', views.post_list, name='post_list_by_category'),
    path('post/<int:id>', views.post_detail, name='post_detail'),
    path('post/<int:id>/comment', views.post_comment, name='post_comment'),
    path('contact-us/', views.ticket, name='ticket'),
    path('posts/search', views.post_search, name='post_search'),
    path('profile/', views.profile_posts, name='profile_posts'),
    path('profile/create_post', views.create_post, name='create_post'),
    path('profile/delete_post/<int:id>', views.delete_post, name='delete_post'),
    path('profile/edit_post/<int:id>', views.edit_post, name='edit_post'),
    path('profile/delete_image/<int:image_id>', views.delete_image, name='delete_image'),
    path('profile/personal_detail', views.personal_detail, name='personal_detail'),
    path('profile/edit_personal_detail', views.edit_personal_detail, name='edit_personal_detail'),
    path('change_password/', views.change_password, name='change_password'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register, name='register'),

]

blog/forms.py
from django import forms
from .models import Post, Comment, User, Account


# =====================================<< Ticket Form >>=====================================
class TicketForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    subject = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)


# =====================================<< Comment Form >>=====================================
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', 'send_mail']


# =====================================<< Search Form >>=====================================
class SearchForm(forms.Form):
    query = forms.CharField()


# =====================================<< Create Post Form >>=====================================
class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(required=False)
    image2 = forms.ImageField(required=False)
    category = forms.CharField(max_length=250)

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time']


# =====================================<< Login Form >>=====================================
class LoginForm(forms.Form):
    email = forms.EmailField(max_length=250, required=True)
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput)


# =====================================<< User Edit Form >>=====================================
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


# =====================================<< Account Edit Form >>=====================================
class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['job', 'bio', 'date_of_birth', 'image']


# =====================================<< Change Password Form >>=====================================
class ChangePasswordForm(forms.Form):
    password = forms.CharField(required=True)
    new_password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    # def clean_new_password(self):
    #     cd = self.cleaned_data
    #     if cd['new_password'] != cd['confirm_password']:
    #         raise forms.ValidationError("رمز ها تطابق ندارند")
    #     else:
    #         return cd['new_password']


# =====================================<< Register Form >>=====================================
class RegisterForm(forms.ModelForm):
    password = forms.CharField(required=True)
    confirm_password = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    # username = forms.CharField(max_length=100, required=True)
    # first_name = forms.CharField(max_length=250, required=True)
    # last_name = forms.CharField(max_length=250, required=True)
    # email = forms.EmailField(max_length=250, required=True)

blog/views.py
import django.forms
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import *
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity, SearchRank, SearchQuery, SearchVector
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth import password_validation, update_session_auth_hash


# =====================================<< Index View >>=====================================
def index(request):
    return render(request, 'blog/index.html', {})


# =====================================<< Post List View >>=====================================
def post_list(request, category=None):
    posts = Post.published.all()

    if category:
        posts = posts.filter(category__slug=category)

    print(category)

    paginator = Paginator(posts, 6)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Post Detail View >>=====================================
def post_detail(request, id):
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=id)
    comments = post.comments.filter(active=True)

    context = {
        'post': post,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


# =====================================<< Post Search View >>=====================================
def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']

            search_query = SearchQuery(query)
            search_vector = SearchVector('title', 'description')
            search_rank = SearchRank(search_vector, search_query)
            results = Post.published.annotate(search=search_vector, rank=search_rank)\
                .filter(search=search_query).order_by('-rank')

            # results_1 = Post.published.annotate(similarity=TrigramSimilarity('title', query))\
            #     .filter(similarity__gte=0.1)
            # results_2 = Post.published.annotate(similarity=TrigramSimilarity('description', query))\
            #     .filter(similarity__gte=0.1)
            # results = (results_1 | results_2).order_by('-similarity')

    paginator = Paginator(results, 6)
    page_number = request.GET.get('page', 1)
    try:
        results = paginator.page(page_number)
    except PageNotAnInteger:
        results = paginator.page(1)
    except EmptyPage:
        results = paginator.page(paginator.num_pages)

    context = {
        'query': query,
        'posts': results,
    }
    return render(request, 'blog/list.html', context)


# =====================================<< Profile Posts View >>=====================================
def profile_posts(request):
    user = request.user
    posts = Post.objects.filter(auther=user)
    context = {
        'posts': posts
    }

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Edit Personal Detail View >>=====================================
def edit_personal_detail(request):
    if request.method == "POST":
        user_form = UserEditForm(request.POST, instance=request.user)
        account_from = AccountEditForm(request.POST, files=request.FILES, instance=request.user.account)
        print(user_form.is_valid(), account_from.is_valid())
        if user_form.is_valid() and account_from.is_valid():

            if request.FILES['image']:
                old_image = request.user.account.image
                storage, path = old_image.storage, old_image.path
                storage.delete(path)
                print(old_image)

            user_form.save(commit=True)
            account_from.save(commit=True)
            return redirect('blog:personal_detail')
    else:
        user_form = UserEditForm(instance=request.user)
        account_from = AccountEditForm(instance=request.user.account)

    return render(request, 'forms/edit_personal_detail.html', {})


# =====================================<< Logout View >>=====================================
def change_password(request):
    user = request.user
    if request.method == "POST":
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            password = cd['password']
            new_password = cd['new_password']
            confirm_password = cd['confirm_password']
            if user.check_password(password):
                user.set_password(new_password)
                update_session_auth_hash(request, user)
                user.save()
                print("با موفقیت عوض شد")
            else:
                return HttpResponse("رمز فعلی را اشتباه وارد کردید.")
    else:
        form = ChangePasswordForm()

    return render(request, 'forms/change_password.html', {})


# =====================================<< Profile Personal Detail View >>=====================================
def personal_detail(request):
    return render(request, 'blog/profile-personal.html', {})


# =====================================<< Login View >>=====================================
def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            cd = form.cleaned_data
            username = User.objects.get(email=cd['email'].lower()).username
            print(username)
            user = authenticate(request, username=username, password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blog:profile_posts')
                else:
                    return HttpResponse("Your account is disabled.")
            else:
                return HttpResponse('User Not Found.(user or pass is wrong)')
    else:
        form = LoginForm()

    return render(request, 'forms/login.html', {'form': form})


# =====================================<< Logout View >>=====================================
def logout_user(request):
    logout(request)
    return redirect('blog:post_list')


# =====================================<< Login View >>=====================================
def register(request):

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = form.save(commit=False)
            user.set_password(cd['password'])
            user.save()
            Account.objects.create(user=user)

            return redirect('blog:login')
    else:
        form = RegisterForm(request.POST)

    return render(request, 'forms/register.html', {'form': form})


# =====================================<< Create Post View >>=====================================
def create_post(request):
    categories = Category.objects.all()

    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            # print(cd)

            post = form.save(commit=False)
            post.auther = request.user
            post.category = Category.objects.get(name=cd['category'])
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)

    else:
        form = CreatePostForm()

    return render(request, 'blog/create-post.html', {'form': form, 'categories': categories})


# =====================================<< Edit Post View >>=====================================
def edit_post(request, id):
    post = get_object_or_404(Post, id=id)
    categories = Category.objects.all()
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            cd = form.cleaned_data
            post = form.save(commit=False)
            post.auther = request.user
            post.save()

            if file := cd['image1']:
                Image.objects.create(post=post, image_file=file)

            if file := cd['image2']:
                Image.objects.create(post=post, image_file=file)
    else:
        form = CreatePostForm(instance=post)

    context = {
        'form': form,
        'post': post,
        'categories': categories
    }

    return render(request, 'blog/create-post.html', context)


# =====================================<< Delete Post View >>=====================================
def delete_post(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()

    posts = Post.published.filter(auther=request.user)
    context = {
        'posts': posts
    }

    print(posts)
    if not post.id:
        return redirect('blog:profile_posts')

    return render(request, 'blog/profile-posts.html', context)


# =====================================<< Delete Image View >>=====================================
def delete_image(request, image_id):

    image = get_object_or_404(Image, id=image_id)
    post_id = image.post.id
    image.delete()

    return redirect('blog:edit_post', post_id)


# =====================================<< Ticket View >>=====================================
def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

blog/templates/blog/contact-us.html
{% extends 'parent/base.html' %}

{% block title%}Blog | Contact Us{% endblock %}

{% block content %}
    {% include 'forms/ticket.html' %}
{% endblock %}

blog/templates/blog/create-post.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Create Post{% endblock %}

{% block content %}
    <div class="container">
        <div class="contactus">
            <h2 class="contactus__title">ایجاد پست جدید</h2>
            <form method="post" class="contactus__form" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__phone" class="contactus__label" id="create-post-title" >عنوان</label>
                    <input type="text" id="ticket__phone" required class="ticket__phone" name="title">
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__phone" class="contactus__label" id="create-post-title"  >زمان مطالعه</label>
                    <input type="number"  min="0" id="ticket__phone" required class="ticket__phone" name="reading_time">
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__description" class="contactus__label">متن</label>
                    <textarea name="description" required id="ticket__description" cols="30" rows="10" class="ticket__description" ></textarea>
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <label for="ticket__category" class="contactus__label" >دسته بندی</label>
                    <select name="category" class="ticket__category" id="ticket__category" >
                        {% for category in  categories %}
                            <option class="ticket__category-option" value="{{ category }}">{{ category }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="contactus__elemetnt-wrapper">
                    <span class="contactus__label">تصاویر</span>
                    <input name="image1" class="image-upload" type="file" id="" >
                    <input name="image2" class="image-upload" type="file" id="" >
                </div>

                {% if post.images.count %}
                    <div class="contactus__elemetnt-wrapper">
                        <span class="contactus__label">تصاویر موجود</span>
                        <div class="create-posts-image-wrapper">
                            {% for image in post.images.all %}
                                <div class="create-post-image-wrapper">
                                    <img src="{{ image.image_file.url }}" class="create-post-image" alt="">
                                    <a href="{% url 'blog:delete_image' image.id %}" class="delete-image">حذف</a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
{##}
                <input type="submit" class="comment-form__btn" value="ایجاد پست">
            </form>
        </div>
    </div>

{#<input type="file" name="image1" accept="image/*" id="id_image1">#}
{% endblock %}

blog/templates/blog/index.html
{% extends 'parent/base.html' %}

{% block title %}Blog | Index{% endblock %}

blog/templates/blog/list.html
{% extends 'parent/base.html' %}
{% load static %}
{% load jformat %}

{% block title %}Blog | Posts{% endblock %}

{% block content %}
    <main class="main">
        {% include 'partials/search.html' %}

        <section class="container post-section">
            <div class="post_wrapper">
                {% for post in posts %}
                    <div class="post">
                        <a href="{{ post.get_absolute_url }}" class="post__image-wrapper">
                            {% if post.images.all %}
                               <img class="post__image" src="{{ post.images.first.image_file.url }}" alt="#">
                            {% else %}
                               <img class="post__image" src="{% static 'images/image-not-found.png' %}" alt="#">
                            {% endif %}
                        </a>
                        <div class="post__title-wrapper">
                            <a href="{{ post.get_absolute_url }}" class="post__title">{{ post.title }}</a>
                        </div>

                        <div class="post__date-wrapper">
                            <p class="post__date">{{ post.publish|jformat:"%d %Y %B"}}</p>
                            {% if post.reading_time %}
                                <p class="post__reading-time">{{ post.reading_time }} دقیقه زمان مطالعه</p>
                            {% endif %}
                        </div>

                        <p class="post__description">{{ post.description }}</p>

                        <div class="post__line"></div>

                        <div class="post__writer-wrapper">
                            {% if post.auther.account.image %}
                               <img class="post__writer-image" src="{{ post.auther.account.image.url }}" alt="#">
                            {% else %}
                                <img class="post__writer-image" src="{% static 'images/empty-profile.png' %}" alt="#">
                            {% endif %}
                            <a class="post__writer" href="#">{{ post.auther.first_name }} {{ post.auther.last_name }}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </main>

    {% include 'partials/pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/profile-personal.html
{% extends 'parent/base.html' %}
{% load static %}

{% block title %}Profile | Personal Detail{% endblock %}

{% block content %}

    <div class="container">
        <section class="profile">
            <!---------------- Side Bar Start---------------->
            <div class="profile-sidebar">
                {% if request.user.account.image %}
                   <img class="profile-image" src="{{ request.user.account.image.url }}" alt="">
                {% else %}
                   <img class="profile-image" src="{% static 'images/empty-profile.png' %}" alt="">
                {% endif %}
                <a href="{% url 'blog:personal_detail' %}" class="profile-name">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                <ul class="profile-menu">
                    <li class="profile-menu__item"><a class="profile-menu__link" href="{% url 'blog:personal_detail' %}">مشخصات</a></li>
                    <li class="profile-menu__item"><a class="profile-menu__link" href="{% url 'blog:profile_posts' %}">پست ها</a></li>
                </ul>
            </div>
            <!---------------- Side Bar End---------------->

            <div class="profile-content">
                <div class="profile-top">
                    <h3 class="profile-title">مشخصات</h3>
                </div>

                <div class="profile-middle">
                    <a class="profile-middle__link" href="{% url 'blog:change_password' %}">
                        <svg class="profile-middle__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" d="M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                        </svg>

                        <span class="profile-middle__text">تغییر رمز</span>
                    </a>
                    <a class="profile-middle__link" href="{% url 'blog:edit_personal_detail' %}">
                        <svg class="profile-middle__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                        <span class="profile-middle__text">ویرایش مشخصات</span>
                    </a>
                    <a class="profile-middle__link" href="{% url 'blog:logout' %}">
                        <svg class="profile-middle__svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" >
                            <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1012.728 0M12 3v9" />
                        </svg>
                        <span class="profile-middle__text">خروج</span>
                    </a>
                </div>
                <!---------------- Profile Personal Detail Start ---------------->
                <div class="profie-personal">
                    <div>
                        نام کاربری : {{ request.user.username }}
                    </div>

                    <div>
                        نام : {{ request.user.first_name }}
                    </div>

                    <div>
                        نام خانوادگی : {{ request.user.last_name }}
                    </div>

                    <div>
                        ایمیل : {{ request.user.email }}
                    </div>

                    <div>
                        شغل : {{ request.user.account.job }}
                    </div>

                    <div>
                        تاریخ تولد : {{ request.user.account.date_of_birth }}
                    </div>

                    <div>
                        بایو : {{ request.user.account.bio }}
                    </div>

                </div>
                <!---------------- Profile Personal Detail End ---------------->


            </div>
        </section>
    </div>

{% endblock %}

blog/templates/blog/profile-posts.html
{% extends 'parent/base.html' %}
{% load static %}


{% block content %}

<div class="container">
    <section class="profile">
        <!---------------- Side Bar Start---------------->
        <div class="profile-sidebar">
            {% if request.user.account.image %}
               <img class="profile-image" src="{{ request.user.account.image.url }}" alt="">
            {% else %}
               <img class="profile-image" src="{% static 'images/empty-profile.png' %}" alt="">
            {% endif %}
            <a href="{% url 'blog:personal_detail' %}" class="profile-name">{{ request.user.first_name }} {{ request.user.last_name }}</a>
            <ul class="profile-menu">
                <li class="profile-menu__item"><a class="profile-menu__link" href="{% url 'blog:personal_detail' %}">مشخصات</a></li>
                <li class="profile-menu__item"><a class="profile-menu__link" href="{% url 'blog:profile_posts' %}">پست ها</a></li>
            </ul>
        </div>
        <!---------------- Side Bar End---------------->

        <div class="profile-content">

            <!---------------- Profile Posts Start---------------->
            <div class="profile-posts">
                    <div class="profile-top">
                        <h3 class="profile-title">پست ها ({{ posts.count }})</h3>
                        <a href="{% url 'blog:create_post' %}" class="profile-add-post">اضافه کردن پست (+)</a>
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th>ردیف</th>
                                <th>مشاهده</th>
                                <th>وضعیت</th>
                                <th>عملیات</th>
                            </tr>
                        </thead>

                        <tbody>

                            {% for post in posts %}
                                <tr>
                                    <td class="td1">{{ forloop.counter }}</td>
                                    <td class="td2"><a class="table-link" href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
                                    <td class="td3"><span class="status"
                                                          style="{% if post.status == "DF" %}background-color:#749bc2;{% elif post.status == "RJ"%}background-color:darkred;{% endif %}">{{ post.status }}</span></td>
                                    <td class="profile-operation-svg-wrapper td4">
                                        <a href="{% url 'blog:delete_post' post.id %}">
                                            <svg class="profile-operation-svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                                            </svg>
                                        </a>
                                        <a href="{% url 'blog:edit_post' post.id %}">
                                            <svg class="profile-operation-svg" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                                <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                                            </svg>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

{#            <form method="post" class="delete-warning" id="delete-warning">#}
{#                {% csrf_token %}#}
{#                <h1 class="warning-title">آیا از حذف مطمئن هستید؟</h1>#}
{#                <div class="delete-btn-wrapper">#}
{#                    <a href="#" class="delete-btn" id="delete-cancel">انصراف</a>#}
{#                    <input type="submit" class="delete-btn" id="delete-accept" value="delete">#}
{#                </div>#}
{#            </form>#}
            <!---------------- Profile Posts End---------------->


        </div>
    </section>
</div>
{% endblock %}